# This is a basic workflow to help you get started with Actions

name: check_workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Single line that runs a shell file
        run: sh ./yamlshellfile.sh
      - name: Run a multi-line script
        run: echo 'this is not multiline anymore'
